cc_library(
    name = "deform_params",
    hdrs = [
        "visualizer_params.h",
        "lcm_channels.h",
        "elastic_sim_params.h",
        "elastoplastic_sim_params.h",
        "elastoplastic_c3_options.h",
        "spring_damper_model_params.h",
    ],
    deps = ["//solvers:c3"],
    visibility = ["//visibility:public"],
)
