cc_library(
    name = "visualizer_params",
    hdrs = ["visualizer_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "lcm_channels",
    hdrs = ["lcm_channels.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "elastic_sim_params",
    hdrs = ["elastic_sim_params.h"],
    visibility = ["//visibility:public"],
)
