cc_library(
    name = "deform_params",
    hdrs = [
        "deform_settings.h",
        "visualizer_params.h",
        "lcm_channels.h",
        "elastic_sim_params.h",
        "elastoplastic_sim_params.h",
        "elastoplastic_sc3_options.h",
        "spring_damper_model_params.h",
        "osc_params.h",
        "reduced_model_params.h",
    ],
    deps = [
        "@c3//:libc3",
        "//examples/sampling_c3/parameter_headers:osc_params",
        "//examples/sampling_c3/parameter_headers:sampling_c3_options",
    ],
    visibility = ["//visibility:public"],
)
