# -*- mode: python -*-
# vi: set ft=python :
package(default_visibility = ["//visibility:public"])

cc_library(
    name = "trifinger_urdf",
    data = glob([
        "models/urdf/**",
        "models/urdf/meshes/**",
        "models/cube/**",
    ]),
)

cc_binary(
    name = "trifinger_simulation",
    srcs = ["trifinger_simulation.cc"],
    deps = [
        "//common:find_resource",
        "//examples/trifinger/parameter_headers:trifinger_lcm_channels",
        "//examples/trifinger/parameter_headers:trifinger_sim_params",
        "//multibody:utils",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "trifinger_visualizer",
    srcs = ["trifinger_visualizer.cc"],
    data = [
        ":trifinger_urdf",
    ],
    deps = [
        "//common:find_resource",
        "//examples/trifinger/parameter_headers:trifinger_lcm_channels",
        "//examples/trifinger/parameter_headers:trifinger_sim_params",
        "//examples/trifinger/systems:lcm_visualization_systems",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "trifinger_osc_controller",
    srcs = ["trifinger_osc_controller.cc"],
    data = [
        ":trifinger_urdf",
    ],
    deps = [
        "//common:eigen_utils",
        "//common:find_resource",
        "//examples/trifinger/parameter_headers:trifinger_lcm_channels",
        "//examples/trifinger/parameter_headers:trifinger_osc_controller_params",
        "//examples/trifinger/systems:fingertips_target_position_receiver",
        "//examples/trifinger/systems:fingertips_target_traj_demultiplexer",
        "//examples/trifinger/systems:trifinger_joint_friction_compensation",
        "//lcm:lcm_trajectory_saver",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//solvers:solver_options_io",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers/osc:operational_space_control",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

py_binary(
    name = "simulate_trifinger",
    srcs = ["simulate_trifinger.py"],
    data = [":trifinger_urdf"],
    deps = [
        "//bindings/pydairlib",
        "@drake//bindings/pydrake",
    ],
)

py_binary(
    name = "simulate_trifinger_lcm",
    srcs = ["simulate_trifinger_lcm.py"],
    data = [":trifinger_urdf"],
    deps = [
        "//bindings/pydairlib",
        "@drake//bindings/pydrake",
    ],
)

py_binary(
    name = "lcm_control_demo",
    srcs = ["lcm_control_demo.py"],
    data = [":trifinger_urdf"],
    deps = [
        "//bindings/pydairlib",
        "@drake//bindings/pydrake",
    ],
)

py_binary(
    name = "start_logging",
    srcs = ["start_logging.py"],
)

#cc_binary(
#    name = "run_impedance_controller",
#    srcs = ["run_impedance_controller.cc"],
#    data = [
#        ":trifinger_urdf",
#    ],
#    deps = [
#        "//common:eigen_utils",
#        "//common:find_resource",
#        "//examples/trifinger/parameter_headers:trifinger_impedance_controller_params",
#        "//examples/trifinger/parameter_headers:trifinger_lcm_channels",
#        "//examples/trifinger/systems:fingertips_target_position_receiver",
#        "//examples/trifinger/systems:trifinger_impedance_control",
#        "//multibody:utils",
#        "//systems:robot_lcm_systems",
#        "//systems:system_utils",
#        "//systems/framework:lcm_driven_loop",
#        "//systems/primitives",
#        "@drake//:drake_shared_library",
#        "@gflags",
#    ],
#)

cc_library(
    name = "trifinger_utils",
    srcs = ["trifinger_utils.cc"],
    hdrs = ["trifinger_utils.h"],
    data = [
        ":trifinger_urdf",
    ],
    deps = [
        "//common",
        "//common:math_utils",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "trifinger_sampling_c3_controller",
    srcs = ["trifinger_sampling_c3_controller.cc"],
    data = [
        ":trifinger_urdf",
    ],
    deps = [
        "//common",
        "//examples/sampling_c3:goal_generator",
        "//examples/sampling_c3/parameter_headers:sampling_c3_controller_params",
        "//examples/sampling_c3/parameter_headers:lcm_channels",
        "//lcm:lcm_trajectory_saver",
        "//examples/trifinger:trifinger_utils",
        "//examples/trifinger/systems:trifinger_kinematics",
        "//systems/senders:sample_buffer_sender",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers:sampling_c3_controller",
        "//systems/framework:lcm_driven_loop",
        "//systems/trajectory_optimization:c3_output_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)
