package(default_visibility = ["//visibility:public"])

cc_library(
    name = "iC3_trajectory_generator",
    srcs = [
        "iC3_trajectory_generator.cc",
    ],
    hdrs = [
        "iC3_trajectory_generator.h",
    ],
    deps = 
    [
        "//common:find_resource",
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "@c3//:libc3",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
        "//examples/iC3:iC3_options",
    ],
)

cc_library(
    name = "timed_gate",
    srcs = [
        "timed_gate.cc",
    ],
    hdrs = [
        "timed_gate.h",
    ],
    deps = 
    [
        "//common:find_resource",
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "//multibody:utils",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
        "//examples/iC3:iC3_options",
    ],
)

cc_library(
    name = "c3_goal_generator",
    srcs = [
        "c3_goal_generator.cc",
    ],
    hdrs = [
        "c3_goal_generator.h",
    ],
    deps = 
    [
        "//common:find_resource",
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "@c3//:libc3",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
        "//examples/iC3:iC3_options",
    ],
)

cc_library(
    name = "c3_trajectory_generator",
    srcs = [
        "c3_trajectory_generator.cc",
    ],
    hdrs = [
        "c3_trajectory_generator.h",
    ],
    deps = [
        "//systems:franka_kinematics",
        "//common:find_resource",
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "//multibody:utils",
        "@c3//:libc3",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)


cc_library(
    name = "ic3_timing_system",
    srcs = [
        "iC3_timing_system.cc",
    ],
    hdrs = [
        "iC3_timing_system.h",
    ],
    deps = [
        "//common:find_resource",
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "//systems/framework:vector",
        "//examples/iC3:iC3_options",
        "//examples/iC3/plate/parameter_headers:franka_plate_controller_params",
        "//examples/iC3/trifinger/parameter_headers:trifinger_controller_params",
        "@drake//:drake_shared_library",
    ],
)