package(default_visibility = ["//visibility:public"])

cc_library(
    name = "urdfs",
    data = glob([
        "urdf/**",
    ]),
)

cc_library(
    name = "parameters",
    data = glob([
        "parameters/*.yaml",
    ]),
)

cc_binary(
    name = "trajectory_visualizer_plate",
    srcs = ["trajectory_visualizer_plate.cc"],
    data = [
        ":urdfs",
        "//examples/cube_flip:parameters",
    ],
    deps = [
        "//examples/cube_flip/parameter_headers:trajectory_visualizer_params",
        "//examples/cube_flip:trajectory_lcm_parser_plate",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)

cc_binary(
    name = "trajectory_visualizer_hand",
    srcs = ["trajectory_visualizer_hand.cc"],
    data = [
        ":urdfs",
        "//examples/cube_flip:parameters",
        "@drake_models//:allegro_hand_description",
    ],
    deps = [
        "//examples/cube_flip/parameter_headers:trajectory_visualizer_params",
        "//examples/cube_flip:trajectory_lcm_parser_hand",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)

cc_binary(
    name = "trajectory_visualizer_point_hand",
    srcs = ["trajectory_visualizer_point_hand.cc"],
    data = [
        ":urdfs",
        "//examples/cube_flip:parameters",
        "@drake_models//:allegro_hand_description",
    ],
    deps = [
        "//examples/cube_flip/parameter_headers:trajectory_visualizer_params",
        "//examples/cube_flip:trajectory_lcm_parser_point_hand",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)

cc_library(
    name = "trajectory_lcm_parser_plate",
    srcs = ["trajectory_lcm_parser_plate.cc"],
    hdrs = ["trajectory_lcm_parser_plate.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/cube_flip/parameter_headers:trajectory_visualizer_params",
    ],
)

cc_library(
    name = "trajectory_lcm_parser_hand",
    srcs = ["trajectory_lcm_parser_hand.cc"],
    hdrs = ["trajectory_lcm_parser_hand.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/cube_flip/parameter_headers:trajectory_visualizer_params",
    ],
)

cc_library(
    name = "trajectory_lcm_parser_point_hand",
    srcs = ["trajectory_lcm_parser_point_hand.cc"],
    hdrs = ["trajectory_lcm_parser_point_hand.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/cube_flip/parameter_headers:trajectory_visualizer_params",
    ],
)

cc_binary(
    name = "franka_plate_sim",
    srcs = ["franka_plate_sim.cc"],
    data = [
        ":urdfs",
        "@drake_models//:franka_description",
    ],
    deps = [
        ":parameters",
        "//common",
        "//examples/franka/systems:franka_systems",
        "//examples/cube_flip/parameter_headers:franka_plate_lcm_channels",
        "//examples/cube_flip/parameter_headers:franka_plate_sim_params",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        "@drake//:drake_shared_library",
        "@gflags",

    ],
)

cc_binary(
    name = "franka_plate_osc_controller",
    srcs = ["franka_plate_osc_controller.cc"],
    data = [
        ":urdfs",
        "@drake_models//:franka_description",
    ],
    deps = [
        ":parameters",
        "//examples/cube_flip/parameter_headers:franka_plate_osc_controller_params",
        "//examples/cube_flip/parameter_headers:franka_plate_lcm_channels",
        "//common",
        "//examples/franka/systems:franka_systems",
        "//lcm:lcm_trajectory_saver",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/controllers/osc:operational_space_control",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "franka_plate_controller",
    srcs = ["franka_plate_controller.cc"],
    data = [
        ":urdfs",
        "@drake_models//:franka_description",
    ],
    deps = [
        ":parameters",
        "//common",
        "//systems/senders:c3_state_sender",
        "//lcm:lcm_trajectory_saver",
        "//solvers:c3",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/controllers:c3_controller",
        "//systems/controllers:lcs_factory_system",
        "//systems/controllers/osc:operational_space_control",
        "//systems:franka_kinematics",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        "//systems/trajectory_optimization:c3_output_systems",
        "@drake//:drake_shared_library",
        "//examples/cube_flip/parameter_headers:franka_plate_controller_params",
        "//examples/cube_flip/parameter_headers:franka_plate_lcm_channels",
        "//examples/cube_flip/parameter_headers:iC3_options",
        "//examples/cube_flip/systems:iC3_trajectory_generator",
        "//examples/cube_flip/systems:c3_goal_generator",
        "//examples/cube_flip/systems:c3_trajectory_generator",
        "//examples/cube_flip/systems:timed_gate",
        "//systems/controllers:ic3_tracking_controller",
        "@gflags",
    ],
)

cc_binary(
    name = "franka_plate_visualizer",
    srcs = ["franka_plate_visualizer.cc"],
    data = [
        ":urdfs",
        "@drake_models//:franka_description",
    ],
    deps = [
        ":parameters",
        "//examples/cube_flip/parameter_headers:franka_plate_lcm_channels",
        "//examples/cube_flip/parameter_headers:franka_plate_sim_params",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)
