osx_build_task:
  timeout_in: 120m
  osx_instance:
    image: mojave-xcode-10.1
  setup_script:
    - wget --quiet -O drake_binary_brewfile "https://raw.githubusercontent.com/RobotLocomotion/drake/21b41f89e4d893635098987639100305131b9569/setup/mac/binary_distribution/Brewfile"
    - wget --quiet -O drake_source_brewfile "https://raw.githubusercontent.com/RobotLocomotion/drake/21b41f89e4d893635098987639100305131b9569/setup/mac/source_distribution/Brewfile"
    - sed -i '' 's#^brew 'kcov'$##g' drake_source_brewfile
    - cat drake_source_brewfile
    - cat drake_binary_brewfile

  test_script:
    - bazel build ...
    - bazel test ...

