build_jammy_task:
  timeout_in: 120m
  container:
    image: docker.io/michaelposa/jammy-dair-base:latest
    registry_config: ENCRYPTED[!d6dc09b37f70c71314fbd39ba44a49c65dd0dbf952e75f47d36a1c25decf2961f176c6ce22fa5ba41784ea6a694597c6!]
    cpu: 2
    memory: 4G
  test_script:
    - export CC=clang-12
    - export CXX=clang++-12
    - bazel build
      --local_resources=24000,8
      --jobs=8 
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - bazel test
      --local_resources=24000,8
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...

drake_master_build_task:
  timeout_in: 120m
  container:
    image: docker.io/michaelposa/jammy-dair-base
    registry_config: ENCRYPTED[!d6dc09b37f70c71314fbd39ba44a49c65dd0dbf952e75f47d36a1c25decf2961f176c6ce22fa5ba41784ea6a694597c6!]
    cpu: 2
    memory: 4G
  allow_failures: true
  test_script:
    - git clone https://github.com/RobotLocomotion/drake.git ../drake
    - export DAIRLIB_LOCAL_DRAKE_PATH=$PWD/../drake
    - bazel build
      --local_resources=24000,8
      --jobs=8 
      //...
    - bazel test
      --local_resources=24000,8
      --jobs=8 
      //...
