
osx_build_task:
  timeout_in: 120m
  osx_instance:
    image: mojave-xcode-10.1
  setup_script:
    - /usr/local/bin/pip2 install --upgrade --requirement protobuf
    - /usr/local/bin/pip3 install --upgrade --requirement protobuf

  test_script:
    - python tmp.py
