osx_build_task:
  timeout_in: 120m
  osx_instance:
    image: mojave-xcode-10.1
  setup_script:
    - brew tap bazelbuild/tap
    - brew tap-pin bazelbuild/tap
    - brew install bazelbuild/tap/bazel
    - brew install diffstat
    - brew install doxygen
    - brew install freetype
    - brew install graphviz
    - brew install kcov
    - brew install llvm@6
    - brew install patchutils
    - brew install pkg-config
  test_script:
    - bazel build ...
    - bazel test ...

