registry_config: ENCRYPTED[!94f86760cec71d7acb7bb218bdf4689cdb6cba0e84dc52bc0b8aadcebd9221652ed7e7d11b8bc0752fc1abbc55db18e7!]

build_jammy_task:
  timeout_in: 120m
  container:
    image: docker.io/michaelposa/jammy-dairlib-base
    cpu: 8
    memory: 24
  test_script:
    - export CC=clang-12
    - export CXX=clang++-12
    - bazel build
      --local_ram_resources=24000
      --local_cpu_resources=8
      --jobs=8 
      //...
    - bazel test
      --local_ram_resources=24000
      --local_cpu_resources=8
      //...

drake_master_build_task:
  timeout_in: 120m
  container:
    image: docker.io/michaelposa/jammy-dairlib-base
    cpu: 8
    memory: 24
  allow_failures: true
  test_script:
    - git clone https://github.com/RobotLocomotion/drake.git ../drake
    - export DAIRLIB_LOCAL_DRAKE_PATH=$PWD/../drake
    - bazel build
      --local_ram_resources=24000
      --local_cpu_resources=8
      --jobs=8 
      //...
    - bazel test
      --local_ram_resources=24000
      --local_cpu_resources=8
      --jobs=8 
      //...
