build_task:
  timeout_in: 120m
  container:
    dockerfile: install/bionic/Dockerfile
    cpu: 8
    memory: 24
  test_script: bazel build ... && bazel test ...
drake_master_build_task:
  timeout_in: 120m
  container:
    dockerfile: install/bionic/LocalDrakeDockerfile
    cpu: 8
    memory: 24
  env:
    DAIRLIB_LOCAL_DRAKE_PATH=$PWD/../drake/
  test_script: cd ../drake/ && git pull && cd ../dairlib/ && bazel build ... && bazel test ...  
