build_task:
  timeout_in: 120m
  container:
    dockerfile: install/bionic/Dockerfile
    cpu: 8
    memory: 24
  test_script:
    - bazel build
      --define=WITH_SNOPT=OFF
      --local_resources=24000,8,1.0 --jobs=8 
      --spawn_strategy=sandboxed
      --strategy=Javac=sandboxed
      --genrule_strategy=sandboxed
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - bazel test
      --define=WITH_SNOPT=OFF
      --local_resources=24000,8,1.0 --jobs=8 
      --spawn_strategy=sandboxed
      --strategy=Javac=sandboxed
      --genrule_strategy=sandboxed
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
drake_master_build_task:
  timeout_in: 120m
  container:
    dockerfile: install/bionic/Dockerfile
    cpu: 8
    memory: 24
  allow_failures: true
  test_script:
    - git clone https://github.com/RobotLocomotion/drake.git ../drake
    - export DAIRLIB_LOCAL_DRAKE_PATH=$PWD/../drake
    - bazel build
      --define=WITH_SNOPT=OFF
      --local_resources=24000,8,1.0 --jobs=8 
      --spawn_strategy=sandboxed
      --strategy=Javac=sandboxed
      --genrule_strategy=sandboxed
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
    - bazel test
      --define=WITH_SNOPT=OFF
      --local_resources=24000,8,1.0 --jobs=8 
      --spawn_strategy=sandboxed
      --strategy=Javac=sandboxed
      --genrule_strategy=sandboxed
      --remote_http_cache=http://$CIRRUS_HTTP_CACHE_HOST
      //...
