## MODULE.bazel
module(
    name = "dairlib"
)

drake_dep_repositories = use_extension(
    "@drake//tools/workspace:default.bzl",
    "drake_dep_repositories",
)

# If you don't want to support building on macOS, you may remove the next line.
# Note that it must appear prior to loading "rules_cc", per the documentation:
#  https://github.com/bazelbuild/apple_support?tab=readme-ov-file#bazel-7-setup
bazel_dep(name = "apple_support", version = "1.23.1")

# Add the Bazel rules we need.
bazel_dep(name = "rules_cc", version = "0.1.1")
bazel_dep(name = "rules_python", version = "1.2.0")
bazel_dep(name = "bazel_skylib", version = "1.7.1")
bazel_dep(name = "rules_foreign_cc", version = "0.15.1")
bazel_dep(name = "platforms", version = "1.0.0")

use_repo(
    drake_dep_repositories,
    "blas",
    "buildifier",
    "drake_models",
    "eigen",
    "fmt",
    "gflags",
    "glib",
    "gtest",
    "lapack",
    "lcm",
    "meshcat",
    "mosek",
    "opencl",
    "pybind11",
    "pycodestyle",
    "snopt",
    "spdlog",
    "styleguide",
    "x11",
    "zlib",
    "gurobi",
)

bazel_dep(name = "gazelle", version = "0.44.0")

bazel_dep(name = "osqp", version = "0.6.3.bcr.2")

# Use gurobi_cxx, which Drake deprecated
gurobi_extension = use_extension("@dairlib//tools/workspace/gurobi:repository.bzl", "gurobi_extension")
use_repo(gurobi_extension, "my_gurobi")

# Replace Drake's Gurobi repository with ours.
override_repo(
    drake_dep_repositories,
    gurobi = "my_gurobi",
)

drake_models_extension = use_extension("@dairlib//tools/workspace/drake_models:repository.bzl", "drake_models_extension")
use_repo(drake_models_extension, "my_drake_models")

override_repo(
    drake_dep_repositories,
    drake_models = "my_drake_models",
)

# Here we introduce Drake as a module dependency, but note that Drake is not
# published to any Bazel registry. Below, we'll override it with a github
# source archive.
bazel_dep(name = "drake")

bazel_dep(name = "inekf")

# By default, this example always uses the latest Drake master branch.

# To use a local version of drake, use
# build --override_module=drake=/home/user/stuff/drake
# this will also work to override inekf 

# You can also use DRAKE_COMMIT to choose a Drake release; e.g.:
DRAKE_VERSION = "v1.42.0"
DRAKE_CHECKSUM = "d860c15f50397c8a946fcc79e0a58a91ebc56f2189ef9edfcac929aa04157f8b"

# Before changing the DRAKE_VERSION, temporarily uncomment the next line so that Bazel
# displays the suggested new value for the CHECKSUM.
# DRAKE_CHECKSUM = "0" * 64

# This declares the `@drake` module as a source code archive from github.
# See README.md for instructions to use a local path, instead.
archive_override(
    module_name = "drake",
    urls = [x.format(DRAKE_VERSION) for x in [
        "https://github.com/RobotLocomotion/drake/archive/{}.tar.gz",
    ]],
    sha256 = DRAKE_CHECKSUM,
    strip_prefix = "drake-{}".format(DRAKE_VERSION.lstrip("v")),
)

INEKF_COMMIT = "297c308e50fa599af92ce3bd5f11d71e2bf8af69"
INEKF_CHECKSUM = "c5a056ce00e1625e52f5a71b1d5c202acd53c1a8c7bca33da458db1e4f3f2edf"


# Before changing the COMMIT, temporarily uncomment the next line so that Bazel
# displays the suggested new value for the CHECKSUM.
#INEKF_CHECKSUM = "0" * 64

# This declares the `@inekf` module as a source code archive from github.
archive_override(
    module_name = "inekf",
    urls = [x.format(INEKF_COMMIT) for x in [
        "https://github.com/DAIRLab/invariant-ekf/archive/{}.tar.gz",
    ]],
    sha256 = INEKF_CHECKSUM,
    strip_prefix = "invariant-ekf-{}".format(INEKF_COMMIT),
)

# Use the host system /usr/bin/python3.
python_repository = use_repo_rule(
    "@drake//tools/workspace/python:repository.bzl",
    "python_repository",
)

python_repository(
    name = "python",
    linux_interpreter_path = "/usr/bin/python3",
    requirements_flavor = "build",
)

register_toolchains("@python//:all")

# Build mujoco
mujoco_extension = use_extension("@dairlib//tools/workspace/mujoco:repository.bzl", "mujoco_extension")
use_repo(mujoco_extension, "mujoco")

# glfw dependency for mujoco
bazel_dep(name = "glfw", version = "3.3.9.bcr.1")

# libomp for OpenMP on macOS
libomp_extension = use_extension("@dairlib//tools/workspace/libomp:repository.bzl", "libomp_extension")
use_repo(libomp_extension, "libomp")

# Hedron's Compile Commands Extractor for Bazel
# https://github.com/hedronvision/bazel-compile-commands-extractor
bazel_dep(name = "hedron_compile_commands", dev_dependency = True)
git_override(
    module_name = "hedron_compile_commands",
    remote = "https://github.com/mikael-s-persson/bazel-compile-commands-extractor",
    commit = "f5fbd4cee671d8d908f37c83abaf70fba5928fc7"
)
