//
// Created by brian on 5/18/22.
//

#ifndef DAIRLIB_EXAMPLES_CASSIE_OSC_HIP_YAW_TRAJ_GEN_H_
#define DAIRLIB_EXAMPLES_CASSIE_OSC_HIP_YAW_TRAJ_GEN_H_

class hip_yaw_traj_gen {

};

#endif //DAIRLIB_EXAMPLES_CASSIE_OSC_HIP_YAW_TRAJ_GEN_H_
