# config.yaml
# This is a sample config file for the inference script learner.py
# Pass the config file to the inference script learner.py using the --config flag
use_wandb: true
model_type: UNet
optimizer: adam
shuffle: true
num_workers: 5
split_ratio: [0.1, 0.1, 0.8]
batch_size: 64
lr: 5e-4
patience: 10
num_epochs: 10
loss: huber
save_model_freq: 15
val_freq: 5
run_name: testing_yaml_parsing
