package(default_visibility = ["//visibility:public"])


cc_library(
    name = "franka_plate_osc_controller_params",
    hdrs = ["franka_plate_osc_controller_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "franka_plate_lcm_channels",
    hdrs = ["franka_plate_lcm_channels.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "franka_plate_sim_params",
    hdrs = ["franka_plate_sim_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "franka_plate_controller_params",
    hdrs = ["franka_plate_controller_params.h"],
    visibility = ["//visibility:public"],
)