load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cassie_elevation_mapping_lcm_diagram",
    srcs = ["cassie_elevation_mapping_lcm_diagram.cc"],
    hdrs = ["cassie_elevation_mapping_lcm_diagram.h"],
    deps = [
        "//examples/Cassie:cassie_utils",
        "//examples/perceptive_locomotion:cassie_perception_utils",
        "//lcmtypes:lcmt_robot",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/perception:camera_utils",
        "//systems/perception:elevation_mapping_system",
        "//systems/perception:perceptive_locomotion_preprocessor",
        "//systems/perception/pointcloud:lcm_to_pcl_point_cloud",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "cassie_realsense_driver_diagram",
    srcs = ["cassie_realsense_driver_diagram.cc"],
    hdrs = ["cassie_realsense_driver_diagram.h"],
    deps = [
        "//examples/Cassie:cassie_utils",
        "//examples/perceptive_locomotion:cassie_perception_utils",
        "//lcmtypes:lcmt_robot",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/perception:camera_utils",
        "//systems/perception:elevation_mapping_system",
        "//systems/perception:perceptive_locomotion_preprocessor",
        "//systems/perception/pointcloud:lcm_to_pcl_point_cloud",
        "//systems/perception/realsense:realsense_point_cloud_subscriber",
        "//systems/perception/realsense:rs_interface",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "diagrams",
    deps = [
        ":cassie_elevation_mapping_lcm_diagram",
        ":cassie_realsense_driver_diagram",
    ],
)