load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc_core",
    deps = [
        ":constrained_inverse_dynamics_info",
        ":knot_point",
        ":knot_point_state",
        ":timeline",
    ],
)

cc_library(
    name = "constrained_inverse_dynamics_info",
    srcs = ["constrained_inverse_dynamics_info.cc"],
    hdrs = ["constrained_inverse_dynamics_info.h"],
    deps = [
        "//common:find_resource",
        "//multibody:pinocchio_plant",
        "//multibody/kinematic",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "knot_point_state",
    srcs = ["knot_point_state.cc"],
    hdrs = ["knot_point_state.h"],
    deps = [
        ":constrained_inverse_dynamics_info",
        "//common:eigen_utils",
    ],
)

cc_library(
    name = "knot_point",
    srcs = ["knot_point.cc"],
    hdrs = ["knot_point.h"],
    deps = [
        ":constrained_inverse_dynamics_info",
        ":knot_point_state",
    ],
)

cc_library(
    name = "timeline",
    srcs = ["timeline.cc"],
    hdrs = ["timeline.h"],
    deps = [
        ":knot_point",
    ],
)
