# -*- python -*-
load("@drake//tools/install:install.bzl", "install")

package(default_visibility = ["//visibility:public"])

load(
    "@drake//tools/skylark:pybind.bzl",
    "drake_pybind_library",
    "get_drake_py_installs",
    "get_pybind_package_info",
    "pybind_py_library",
)

pybind_py_library(
    name = "systems_py",
    cc_deps = [
        "//examples/perceptive_locomotion/systems:meshcat_mpc_debug_visualizer",
        "@drake//:drake_shared_library",
    ],
    cc_so_name = "systems",
    cc_srcs = ["systems_py.cc"],
    py_deps = [
        "@drake//bindings/pydrake",
        ":module_py",
    ],
    py_imports = ["."],
)


PACKAGE_INFO = get_pybind_package_info("//bindings")

py_library(
    name = "module_py",
    srcs = [
        "__init__.py",
    ],
    imports = PACKAGE_INFO.py_imports,
    deps = [
        "//bindings/pydairlib:module_py",
    ],
)

PY_LIBRARIES = [
    ":systems_py"
]

# Package roll-up (for Bazel dependencies).
py_library(
    name = "systems",
    imports = PACKAGE_INFO.py_imports,
    deps = PY_LIBRARIES,
)
