cc_library(
    name = "toy_yamls",
    data = glob([
        "*.yaml",
    ]),
)

cc_library(
    name = "toy_system_params",
    hdrs = [
        "toy_system_params.h",
    ],
    deps = [
    ]
)


cc_library( 
  name = "fixed_input",
    srcs = [
        "fixed_input.cc",
    ],
    hdrs = [
        "fixed_input.h",
    ],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
    ],
)

cc_library( 
  name = "lqr_input",
    srcs = [
        "lqr_input.cc",
    ],
    hdrs = [
        "lqr_input.h",
    ],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
    ],
)


cc_library( 
  name = "toy_utils",
    hdrs = [
        "toy_utils.h",
    ],
    data = [
        ":toy_yamls",
    ],
    deps = [
        "//systems/controllers:ic3_tracking_controller",
        ":toy_system_params",
        "//examples/cube_flip/parameter_headers:iC3_options",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "toy_system_controller",
    srcs = [
        "toy_system_controller.cc", 
    ],
    data = [
        "//examples/cube_flip:urdfs",
        ":toy_yamls",
    ],
    deps = [
        "//common",
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        ":fixed_input",
        ":lqr_input",
        ":toy_system_params",
        "//solvers:c3",
        ":toy_utils",
        "//systems/controllers:lcs_factory_system",
        "//examples/cube_flip/parameter_headers:iC3_options",
        "//systems:system_utils",
        "//systems/controllers:ic3_tracking_controller",
        "//systems/framework:lcm_driven_loop",
        "//systems:robot_lcm_systems",
        "@gflags",
    ]
)

cc_binary(
    name = "toy_system_hand_controller",
    srcs = [
        "toy_system_hand_controller.cc", 
    ],
    data = [
        "//examples/cube_flip:urdfs",
        ":toy_yamls",
    ],
    deps = [
        "//common",
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        ":fixed_input",
        ":lqr_input",
        ":toy_system_params",
        "//solvers:c3",
        ":toy_utils",
        "//systems/controllers:lcs_factory_system",
        "//examples/cube_flip/parameter_headers:iC3_options",
        "//systems:system_utils",
        "//systems/controllers:ic3_tracking_controller",
        "//systems/framework:lcm_driven_loop",
        "//systems:robot_lcm_systems",
        "@gflags",
    ]
)

cc_binary(
    name = "toy_system_sim",
    srcs = ["toy_system_sim.cc"],
    data = [
        "//examples/cube_flip:urdfs",
        ":toy_yamls",
    ],
    deps = [
        "//common",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        ":toy_system_params",
        "@drake//:drake_shared_library",
        "@gflags",

    ],
)

cc_binary(
    name = "toy_system_hand_sim",
    srcs = ["toy_system_hand_sim.cc"],
    data = [
        "//examples/cube_flip:urdfs",
        ":toy_yamls",
    ],
    deps = [
        "//common",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        ":toy_system_params",
        "@drake//:drake_shared_library",
        "@gflags",

    ],
)