cc_library(
    name = "sampling_c3_options",
    hdrs = ["sampling_c3_options.h"],
    visibility = ["//visibility:public"],  # Allow all subpackages to use it
    deps = ["//solvers:c3"]
)

cc_library(
    name = "franka_sim_params",
    hdrs = ["franka_sim_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "visualizer_params",
    hdrs = ["visualizer_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "lcm_channels",
    hdrs = ["lcm_channels.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sampling_c3_controller_params",
    hdrs = ["sampling_c3_controller_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "osc_params",
    hdrs = ["osc_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "goal_params",
    hdrs = ["goal_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "sampling_params",
    hdrs = ["sampling_params.h"],
    visibility = ["//visibility:public"],
)

cc_library(
    name = "reposition_params",
    hdrs = ["reposition_params.h"],
    visibility = ["//visibility:public"],
)
