### ROM parameter
# dir_model: "../dairlib_data/goldilocks_models/planning/robot_1/20220417_rom27_big_range_bigger_step_size_6e-3_torque_weight_dominate/robot_1/"                      # rom_option 27
dir_model: "../dairlib_data/goldilocks_models/planning/robot_1/20220510_rom27_big_range_bigger_step_size_5e-3_torque_weight_dominate_com_center/robot_1/"    # rom_option 30

rom_option: 27
model_iter: 1

### Evaluation parameters
dir_data: "../dairlib_data/goldilocks_models/rom_dyn_eval/"

x_min: -0.1
x_max: 0.1
n_samples_x: 20

y_min: 0
y_max: 0
n_samples_y: 1

z_min: 0.6
z_max: 1.1
n_samples_z: 20

save_fig: false