//
// Created by brian on 2/3/25.
//

#ifndef DAIRLIB_SYSTEMS_CONTROLLERS_ID_MPC_COSTS_RELATIVE_POSITION_COST_H_
#define DAIRLIB_SYSTEMS_CONTROLLERS_ID_MPC_COSTS_RELATIVE_POSITION_COST_H_

class relative_position_cost {

};

#endif //DAIRLIB_SYSTEMS_CONTROLLERS_ID_MPC_COSTS_RELATIVE_POSITION_COST_H_
