load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc",
    srcs = ["id_mpc.cc"],
    hdrs = ["id_mpc.h"],
    deps = [
        "//lcm:lcm_trajectory_saver",
        "//systems/controllers/id_mpc/core:id_mpc_core",
    ],
)
