load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc",
    srcs = [
        "constrained_dynamics_info.cc",
        "id_mpc.cc",
        "id_mpc_knot_point.cc",
    ],
    hdrs = glob(["*.h"]),
    deps = [
        "//common:eigen_utils",
        "//common:find_resource",
        "//multibody/kinematic",
        "//solvers:nonlinear_constraint",
        "@drake//:drake_shared_library",
    ],
)
