load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc_walking",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//multibody:box_set",
        "//solvers/admm:convex_polygon_set_constraint",
        "//systems/controllers/footstep_planning:alip_utils",
        "//systems/controllers/id_mpc",
    ],
)
