package(default_visibility = ["//visibility:public"])

filegroup(
    name = "params_yamls",
    visibility = ["//visibility:public"],
    data = ["//examples/deform:parameters"],
)

cc_binary(
    name = "hand_visualizer",
    srcs = ["hand_visualizer.cc"],
    data = [
        "//examples/deform:params_yamls",
        "@drake_models//:allegro_hand_description",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:lcm_channels",
        "//examples/deform/parameter_headers:visualizer_params",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_library(
    name = "deform_utils",
    srcs = ["deform_utils.cc"],
    hdrs = ["deform_utils.h"],
    deps = [
        "//common",
        "//common:math_utils",
        "//examples/deform/parameter_headers:spring_damper_model_params",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "elastic_sim",
    srcs = ["elastic_sim.cc"],
    data = [
        "//examples/deform:params_yamls",
        "@drake_models//:allegro_hand_description",
        ":models",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:lcm_channels",
        "//examples/deform/parameter_headers:elastic_sim_params",
        "//examples/deform/parameter_headers:spring_damper_model_params",
        "//common",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/framework:lcm_driven_loop",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)
