package(default_visibility = ["//visibility:public"])

filegroup(
    name = "params_yamls",
    data = ["//examples/deform:parameters"],
)

cc_library(
    name = "elastoplastic_model_interpreter",
    srcs = [
        "elastoplastic_model_interpreter.cc",
    ],
    hdrs = [
        "elastoplastic_model_interpreter.h",
    ],
    deps = [
        "//lcm:lcm_trajectory_saver",
        "//common",
        "//common:find_resource",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "mpm_model_reducer",
    srcs = [
        "mpm_model_reducer.cc",
    ],
    hdrs = [
        "mpm_model_reducer.h",
    ],
    deps = [
        "//examples/deform/parameter_headers:deform_params",
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "//common",
        "//common:find_resource",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "franka_deform_controller",
    srcs = ["franka_deform_controller.cc"],
    data = [
        ":models",
        "@drake_models//:franka_description",
        "//examples/deform:params_yamls",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:deform_params",
        "//examples/deform:mpm_model_reducer",
        "//systems/controllers:elastoplastic_sampling_c3_controller",
        "//common",
        "//lcm:lcm_trajectory_saver",
        "//systems:franka_kinematics",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/framework:lcm_driven_loop",
        "@drake//:drake_shared_library",
        "//systems/senders:sample_buffer_sender",
        "//systems/senders:senders",
        "@gflags",
    ],
)

cc_binary(
    name = "hand_visualizer",
    srcs = ["hand_visualizer.cc"],
    data = [
        "//examples/deform:params_yamls",
        "@drake_models//:allegro_hand_description",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:deform_params",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "elastoplastic_visualizer",
    srcs = ["elastoplastic_visualizer.cc"],
    data = [
        "//examples/deform:params_yamls",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:deform_params",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@gflags",
    ],
)

cc_binary(
    name = "franka_visualizer",
    srcs = ["franka_visualizer.cc"],
    data = [
        ":models",
        "//examples/deform:params_yamls",
        "@drake_models//:franka_description",
    ],
    deps = [
        "//examples/deform:elastoplastic_model_interpreter",
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:deform_params",
        "//common",
        "//lcm:lcm_trajectory_saver",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:franka_kinematics",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_library(
    name = "deform_utils",
    srcs = ["deform_utils.cc"],
    hdrs = ["deform_utils.h"],
    deps = [
        "//common",
        "//common:math_utils",
        "//examples/deform/parameter_headers:deform_params",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "franka_osc_controller",
    srcs = ["franka_osc_controller.cc"],
    data = [
        ":models",
        "@drake_models//:franka_description",
    ],
    deps = [
        "//examples/deform/parameter_headers:deform_params",
        "//examples/deform:deform_utils",
        "//common",
        "//lcm:lcm_trajectory_saver",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers:gravity_compensator",
        "//systems/controllers/osc:operational_space_control",
        "//systems/framework:lcm_driven_loop",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)

cc_binary(
    name = "elastic_sim",
    srcs = ["elastic_sim.cc"],
    data = [
        "//examples/deform:params_yamls",
        "@drake_models//:allegro_hand_description",
        ":models",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:deform_params",
        "//common",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/framework:lcm_driven_loop",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "elastoplastic_sim",
    srcs = ["elastoplastic_sim.cc"],
    data = [
        "//examples/deform:params_yamls",
        ":models",
    ],
    deps = [
        "//examples/deform:deform_utils",
        "//examples/deform/parameter_headers:deform_params",
        "//common",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/framework:lcm_driven_loop",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)
