package(default_visibility = ["//visibility:public"])

cc_library(
    name = "lcmt_generators",
    srcs = [],
    deps = [
        ":robot_state_generator",
    ],
)

cc_library(
    name = "robot_state_generator",
    srcs = [
        "robot_state_generator.cc",
    ],
    hdrs = [
        "robot_state_generator.h",
    ],
    deps = [
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)