# bouncy ball parameters

# impedance control parameters
translational_stiffness: 200 # 300
rotational_stiffness: 2 # 1
damping_ratio: 1
stiffness_null: 2
damping_null: 1
q_null_desired: [0, 0.36, 0, -2.39, 0, 2.748, 0]
moving_offset: 0 #0.0005
pushing_offset: 0 #-0.001

# c3 parameters
mu: 1                   # changes need to be consistent with urdf
Q_default: 0
Q_finger: 100           # finger xyz cost
Q_ball_x: 2500  #10000
Q_ball_y: 2500  #10000
Q_finger_vel: 10        # translational velocity cost
Q_ball_vel: 0.1         # angular & translational velocity cost
Qnew_finger: 1000000    # Qnew costs
Qnew_ball_x: 1
Qnew_ball_y: 1
R: 0.01                 # torque cost in xyz
G: 0.01
U_default: 1
U_pos_vel: 10           # first 19 diag elements of U
U_u: 1                  # last 3 diag elements of U
q_init_finger: [0, 0, 0.07]
q_init_ball_c3: [1, 0, 0, 0, 0.05, 0.05, 0.03]
dt: 0.015 # 0.03

# initialization/simulation parameters
#q_init_franka: [0.154, 0.401, -0.08, -2.65, -0.33, 3.05, -0.252]
q_init_franka: [0, 0.36, 0, -2.39, 0, 2.748, 0]
q_init_ball: [1, 0, 0, 0] # xyz computed according to x_c, y_c, traj_radius, phase, and ball_radius
#initial_start: [0.4, 0, 0.08]
initial_start: [0.5, 0, 0.12]
initial_finish: [0, 0, 0.08]  # xy computed according to x_c, y_c, traj_radius, and phase
stabilize_time1: 1
move_time: 1
stabilize_time2: 1
sim_dt: 0.0001 # 0.00005

traj_radius: 0.1
phase: 0 # starting at 180 avoids first hard push
x_c: 0.5
y_c: 0
degree_increment: 20
time_increment: 4
hold_order: 1 # 0 for zero order hold, 1 for first order hold

c3_sub_timeout: 0.15
realtime_rate: 0.5

ball_radius: 0.0312           # changes need to be consistent with urdf
finger_radius: 0.01         # changes need to be consistent with urdf
EE_offset: [0, 0, 0.03]     # changes need to be consistent with urdf


# Misc
contact_threshold: 0.0001
period: 2.5
duty_cycle: 0.67
duty_cycle_upwards_ratio: 0.33 # need better name here   (ratio it goes upwards)
enable_heuristic: 0
enable_contact: 1
ball_stddev: 0.01 # standard deviation of 0-mean noise on ball state estimation
test_parameters: [0.02, 0.075, 0.071, 0.07]

# testing
lead_angle: 20 # angle in degrees
enable_adaptive_path: 1 # 0 to use regular path, 1 to use path that adjusts to ball in real time

# filters
dt_filter_length: 10