# bouncy ball parameters

# impedance control parameters
translational_stiffness: 150 # 200
rotational_stiffness: 4 # 2
damping_ratio: 1
stiffness_null: 4 # try changing to 2
damping_null: 4 # try changing to using damping ratio null
q_null_desired: [0, 0.361, 0, -2.223, 0, 2.584, 0]
moving_offset: 0 #0.0005
pushing_offset: 0 #-0.001

# c3 parameters
mu: 1                   # changes need to be consistent with urdf
Q_default: 0
Q_finger: 200           # finger xyz cost
Q_ball_x: 2500  #10000
Q_ball_y: 2500  #10000
Q_finger_vel: 10        # translational velocity cost
Q_ball_vel: 0.1         # angular & translational velocity cost
Qnew_finger: 1000000    # Qnew costs
Qnew_ball_x: 1
Qnew_ball_y: 1
R: 0.01                 # torque cost in xyz
G: 0.01
U_default: 1
U_pos_vel: 10           # first 19 diag elements of U
U_u: 1                  # last 3 diag elements of U
q_init_finger: [0, 0, 0.051] # TODO: Tune this! (used to be 0.7)
#q_init_finger: [0, 0, 0.0399] # parameters that work for wrong EE model
q_init_ball_c3: [1, 0, 0, 0, 0.05, 0.05, 0.03] # last 3 elements don't matter
dt: 0.015 # 0.03

# initialization/simulation parameters
q_init_franka: [0, 0.275, 0, -2.222, 0, 2.497, 0]
q_init_ball: [1, 0, 0, 0] # xyz computed according to x_c, y_c, traj_radius, phase, and ball_radius
initial_start: [0.55, 0, 0.12]
initial_finish: [0, 0, 0.06]  # xy computed according to x_c, y_c, traj_radius, and phase
stabilize_time1: 0.5
move_time: 0.75
stabilize_time2: 0.75
sim_dt: 0.0001 # 0.00005
realtime_rate: 1.0

# trajectory parameters
traj_radius: 0.1
phase: 0 # starting at 180 avoids first hard push
x_c: 0.55
y_c: 0
degree_increment: 20
time_increment: 4
hold_order: 1 # 0 for zero order hold, 1 for first order hold

# if enable_adaptive_path is set to 1, the trajectory above is not used
lead_angle: 20 # angle in degrees
enable_adaptive_path: 1 # 0 to use regular path, 1 to use path that adjusts to ball in real time

# geometry parameters
ball_radius: 0.0315           # changes need to be consistent with urdf AND vision
finger_radius: 0.0195         # changes need to be consistent with BOTH urdfs
EE_offset: [0, 0, 0.0153]     # changes need to be consistent with urdf
table_offset: -0.0301         # chances need to be consistent with BOTH urdfs AND vision
# table_offset: -0.0193         # chances need to be consistent with BOTH urdfs AND vision

# Misc
contact_threshold: 0.01
enable_heuristic: 0
enable_contact: 1
ball_stddev: 0.0001 # standard deviation of 0-mean noise on ball state estimation

# gaiting parameters
period: 3   #2.5
duty_cycle: 0.75 #0.75
duty_cycle_upwards_ratio: 0.33 # need better name here
gait_parameters: [0.02, 0.055, 0.051, 0.049] # try playing with first param here

# filters
dt_filter_length: 10
alpha_p: 0.2
alpha_v: 1