# bouncy ball parameters

# impedance control parameters  # TODO may need to tune these
translational_stiffness: 700 #500, 400
rotational_stiffness: 900
translational_damping_ratio: 1
rotational_damping: 20 # temporary increase for safety #10 to 50

translational_integral_gain: 0
rotational_integral_gain: 0
integrator_clamp: [30, 30, 30, 30, 8, 8, 8]

stiffness_null: 4
damping_null: 4
q_null_desired: [0, 0.361, 0, -2.223, 0, 2.584, 0]
moving_offset: 0 #0.0005
pushing_offset: 0 #-0.001

# c3 parameters
mu: 1                  # changes need to be consistent with urdf
use_full_cost: true        # debugging parameter, if false uses ball location error only to compare current with sample c3 costs.
Q_default: 0
Q_finger: 1000      # finger xyz cost  # TODO tune these
Q_ball_x: 100000 #10000  # TODO tune these
Q_ball_y: 100000  #10000  # TODO tune these
Q_ball_z: 1000
Q_finger_vel: 10  #10        # translational velocity cost  # TODO may need to tune these
Q_ball_vel: 0.1 #0.1         # translational velocity cost  # TODO may need to tune these
R: 0.01                 # torque cost in xyz  # TODO may need to tune these
G: 0.01 #0.1             #ADMM related  # TODO may need to tune these
G_ground: 0.00001
U_default: 1              #ADMM projection step related
U_pos: 1000000 #10000           # first 10 diag elements of U, corresponding to positions  #ADMM projection step related
U_vel: 100   #1000              # next 9 diag elements of U, corresponding to velocities
U_u: 10 #10                  # last 3 diag elements of U, corresponding to control input      #ADMM projection step related
q_init_finger: [0, 0, 0.085] #[0, 0, 0.0775] CHANGED THIS
q_init_ball_c3: [1, 0, 0, 0, 0.05, 0.05, 0.03] # last 3 elements don't matter
dt: 0.015 # 0.03
velocity_limit: 100
orientation_degrees: 0 #15  # TODO may need to tune these, steeper angle can decrease torque on the end effector
axis_option: 1
planning_timestep: 0.1
c3_planned_next_state_timestep: 0.02
horizon_length: 5

# initialization/simulation parameters
q_init_franka: [0, 0.275, 0, -2.222, 0, 2.497, 0]
q_init_ball: [0.847410781, 0.310617894, 0.311017672, -0.385788646] #[0.9239, 0.3827, 0, 0] (2 contacts) #[1, 0, 0, 0] (1 contact) # xyz computed according to x_c, y_c, traj_radius, phase, and ball_radius
initial_start: [0.55, 0 , 0.22]
initial_finish: [0.35, 0.35, 0.07]  # [0.55, 0.53, 0.07] avoids contact between ee and jack when control begins
stabilize_time1: 0.5 #0.5
move_time: 0.75 #0.75
stabilize_time2: 0.75 #0.75
sim_dt: 0.0001 # 0.00005
sim_publish_dt: 0.001   # 1kHz for state publishing matches Franka hardware.
realtime_rate: 0.2

# trajectory parameters
trajectory_type: 1    # 0 to use time-based path, 1 to use adaptive path, 2 to use fixed goal
traj_radius: 0.2
phase: 0
x_c: 0.35
y_c: 0
degree_increment: 30  
time_increment: 1
hold_order: 0 # 0 for zero order hold, 1 for first order hold

# adaptive path specific parameters
lead_angle: 40 #20 angle in degrees

# fixed path specific parameters
fixed_goal_x: 0.55
fixed_goal_y: -0.25

# geometry parameters
jack_half_width: 0.0625       # gives rough size of the jack object
finger_radius: 0.0195         # changes need to be consistent with franka_box and model urdfs
EE_offset: [0, 0, 0.0153]     # changes need to be consistent with franka_box urdf
table_offset: -0.0245 #-0.0245      # chances need to be consistent with franka_box, model urdf, AND vision
model_table_offset: -0.0245 #-0.0245 # changes need to be consistent with model urdf
# number_contact_pairs: 9 #9 contact pairs for cube - 1 for ee-->cube and 8 for each corner-->ground 


#Sampling parameters
force_skip_sampling: false    # flag to skip doing sampling and just run C3 on its own.
sampling_strategy: 2          # Select sampling strategy. 
                              # 0 means radially symmetric sampling on a circle. 
                              # 1 means random sampling on a 2D circle. 
                              # 2 means random sampling on a 3D sphere.
sampling_radius: 0.12         # size of sampling circle; used for both circle perimeter (0, 1) and spherical surface sampling (2).
sample_height: 0.04           # height of sampling circle; used for circle perimeter (0, 1).
min_angle_from_vertical: 0.785    # radians minimum angle from vertical (i.e. closest to top of sphere) used for spherical surface sampling (2).
max_angle_from_vertical: 1.822    # radians maximum angle from vertical (i.e. closest to bottom of sphere) used for spherical surface sampling (2).
num_additional_samples_repos: 2   # number of additional samples to consider when doing repositioning.
num_additional_samples_c3: 1      # number of additional samples to consider when doing C3.
spline_width: 0.12   #0.09
travel_cost_per_meter: 100
travel_speed: 0.5     # desired meters/second of repositioning


#Threading parameters
num_threads: 1     # Total number of threads to use. 0 means use all threads on machine.

#Switching parameters
switching_hysteresis: 400 #150
reposition_fixed_cost: 500    # This needs to be higher than the switching hysteresis to ensure switching
                              # back to C3 once it repositions and reaches a repositioning goal.
finished_reposition_cost: 1000000   # Added cost to repositioning target if travel reached the end of the spline last step.


# Misc
contact_threshold: 0.01
enable_heuristic: 0
enable_contact: 0   #1
ball_stddev: 0.0 # standard deviation of 0-mean noise on ball state estimation

#Visualization
display_rollout_flag: false

# filters
dt_filter_length: 10
alpha_p: 0.2
alpha_v: 1

