# bouncy ball parameters

# impedance control parameters  # TODO may need to tune these
translational_stiffness: 500 # 400
rotational_stiffness: 900
translational_damping_ratio: 1
rotational_damping: 20 # temporary increase for safety #10 to 50

translational_integral_gain: 0
rotational_integral_gain: 0
integrator_clamp: [30, 30, 30, 30, 8, 8, 8]

stiffness_null: 4
damping_null: 4
q_null_desired: [0, 0.361, 0, -2.223, 0, 2.584, 0]
moving_offset: 0 #0.0005
pushing_offset: 0 #-0.001

# c3 parameters
mu: 1                  # changes need to be consistent with urdf
use_full_cost: true        # debugging parameter, if false uses ball location error only to compare current with sample c3 costs.
Q_default: 0
Q_finger: 650      # finger xyz cost  # TODO tune these
Q_ball_x: 100000 #10000  # TODO tune these
Q_ball_y: 100000  #10000  # TODO tune these
Q_ball_z: 0
Q_finger_vel: 10  #10        # translational velocity cost  # TODO may need to tune these
Q_ball_vel: 0.1 #0.1         # translational velocity cost  # TODO may need to tune these
R: 0.01                 # torque cost in xyz  # TODO may need to tune these
G: 0.01 #0.1             #ADMM related  # TODO may need to tune these
U_default: 1              #ADMM projection step related
U_pos_vel: 100 #1000           # first 19 diag elements of U  #ADMM projection step related
U_u: 10 #10                  # last 3 diag elements of U      #ADMM projection step related
q_init_finger: [0, 0, 0.085] #[0, 0, 0.0775] CHANGED THIS
q_init_ball_c3: [1, 0, 0, 0, 0.05, 0.05, 0.03] # last 3 elements don't matter
dt: 0.015 # 0.03
velocity_limit: 100
orientation_degrees: 0 #15  # TODO may need to tune these, steeper angle can decrease torque on the end effector
axis_option: 1

# initialization/simulation parameters
q_init_franka: [0, 0.275, 0, -2.222, 0, 2.497, 0]
q_init_ball: [0.847410781, 0.310617894, 0.311017672, -0.385788646] #[0.9239, 0.3827, 0, 0] (2 contacts) #[1, 0, 0, 0] (1 contact) # xyz computed according to x_c, y_c, traj_radius, phase, and ball_radius
initial_start: [0.55, 0 , 0.12]
initial_finish: [0, 0, 0.07]  # [0, 0, 0.07]  # xy computed according to x_c, y_c, traj_radius, and phase
stabilize_time1: 0.5 #0.5
move_time: 0.75 #0.75
stabilize_time2: 0.75 #0.75
sim_dt: 0.0001 # 0.00005
realtime_rate: 0.2

# trajectory parameters
traj_radius: 0.2
phase: 0
x_c: 0.55
y_c: 0
degree_increment: 30  
time_increment: 1
hold_order: 0 # 0 for zero order hold, 1 for first order hold

# if enable_adaptive_path is set to 1, the trajectory above is not used
lead_angle: 30 #20 angle in degrees
enable_adaptive_path: 1 # 0 to use regular path, 1 to use path that adjusts to ball in real time

# geometry parameters
ball_radius: 0.0625 #0.0625 #0.0315           # changes need to be consistent with sphere urdf, geometry mesh, AND vision  # TODO tune/remove these
finger_radius: 0.0195         # changes need to be consistent with franka_box and model urdfs
EE_offset: [0, 0, 0.0153]     # changes need to be consistent with franka_box urdf
table_offset: -0.0245 #-0.0245      # chances need to be consistent with franka_box, model urdf, AND vision
model_table_offset: -0.0245 #-0.0245 # changes need to be consistent with model urdf
# number_contact_pairs: 9 #9 contact pairs for cube - 1 for ee-->cube and 8 for each corner-->ground 

#Sampling parameters
sampling_radius: 0.12   #Size of sampling circle
sample_height: 0.05
num_additional_samples: 3
spline_width: 0.12   #0.09
travel_cost_per_meter: 100
travel_speed: 0.5     # desired meters/second of repositioning

#Switching parameters
switching_hysteresis: 100


# Misc
contact_threshold: 0.01
enable_heuristic: 0
enable_contact: 0   #1
ball_stddev: 0.0 # standard deviation of 0-mean noise on ball state estimation

#Visualization
display_rollout_flag: false

# filters
dt_filter_length: 10
alpha_p: 0.2
alpha_v: 1

