---
n_envs: 20
eval_seed: 70
train_seed: 90
batch_size: 1024
n_steps_per_update: 254  # this is functionally 254 * n_envs
eval_freq: 512
total_training_steps: 1500000
reward_weights: [0.2, -0.1]
n_eval_episodes: 10

# Terrain Information
terrain_config_path: "./multibody/curriculum_terrain_config.yaml"
curriculum_schedule: [200000, 500000]
blind: False 
terrain_randomize: True
eval_randomize: False # test evaluation on rough terrains as well (False will only test on flat ground)

goal_x: 4.0
