# LCM channels to read data from
channel_x: "CASSIE_STATE_DISPATCHER"
channel_u: "OSC_WALKING"
channel_osc: "OSC_DEBUG_WALKING"
use_archived_lcmtypes: false

# Approximate log time to start at relative to the first timestamp in the log
start_time: 1.0
# Duration of time to plot (seconds, -1 for whole log)
duration: -1

# Plant properties
use_springs: true
use_floating_base: true

# Desired RobotOutput plots
plot_floating_base_positions: false
plot_floating_base_velocities: false
plot_floating_base_velocity_body_frame: false
plot_joint_positions: false
plot_joint_velocities: false
plot_measured_efforts: false
plot_commanded_efforts: false
plot_contact_forces: false
special_positions_to_plot: [ ]
special_velocities_to_plot: [ ]
special_efforts_to_plot: [ ]

# FSM Names
fsm_state_names: [ 'Left Stance (LS)',
                   'Right Stance (RS)',
                   ' ',
                   'Double Support Post Left (DSPL)',
                   'Double Support Post Right (DSPR)' ]

# Foot position plots
foot_positions_to_plot: []
foot_xyz_to_plot: { 'right': [ 0, 2 ], 'left': [ 0, 2 ] }
pt_on_foot_to_plot: 'mid'  # takes value 'front', 'mid', or 'rear'

# Desired osc plots
plot_qp_costs: true
plot_tracking_costs: true
plot_qp_solve_time: true
tracking_datas_to_plot:
#  right_toe_angle_traj: {'dims': [0], 'derivs': ['pos', 'vel', 'accel']}
#  left_toe_angle_traj: {'dims': [0], 'derivs': ['pos', 'vel', 'accel']}
  alip_com_traj: { 'dims': [ 0, 2 ], 'derivs': [ 'pos', 'vel', 'accel' ] }
  swing_ft_traj: { 'dims': [ 0, 1, 2 ], 'derivs': [ 'pos', 'vel', 'accel' ] }
#  pelvis_heading_traj: { 'dims': [ 2 ], 'derivs': [ 'pos', 'vel', 'accel' ] }
#  pelvis_balance_traj: { 'dims': [ 2 ], 'derivs': [ 'pos', 'vel', 'accel' ] }
#  swing_hip_yaw_traj: {'dims': [0], 'derivs': ['accel']}
