package(default_visibility = ["//visibility:public"])

cc_library(
    name = "pinocchio_interface",
    srcs = ["pinocchio_interface.cc"],
    hdrs = ["pinocchio_interface.h"],
    deps = [
        "//multibody:utils",
        "@drake//:drake_shared_library",
        "@pinocchio",
    ],
)

cc_binary(
    name = "pinocchio_utils_test",
    srcs = ["test/pinocchio_utils_test.cc"],
    deps = [":pinocchio_interface"],
)
