# -*- mode: python -*-
# vi: set ft=python :

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "ncqp_solver",
    srcs = ["ncqp_solver.cc"],
    hdrs = ["ncqp_solver.h"],
    deps = [
        ":set_membership_constraint",
        "//solvers:osqp_wrapper",
        "//solvers:qpalm_wrapper",
        "//solvers:qp_data",
        "//solvers:solver_options_io",
        "@drake//:drake_shared_library",
        "@qpalm",
    ],
)

cc_library(
    name = "set_membership_constraint",
    srcs = ["set_membership_constraint.cc"],
    hdrs = ["set_membership_constraint.h"],
    deps = [
        "//solvers:nonlinear_constraint",
    ],
)

cc_library(
    name = "convex_polygon_set_constraint",
    srcs = ["convex_polygon_set_constraint.cc"],
    hdrs = ["convex_polygon_set_constraint.h"],
    deps = [
        ":set_membership_constraint",
        "//geometry:convex_polygon_set",
        "//solvers:osqp_wrapper",
    ],
)

cc_binary(
    name = "ncqp_solver_test",
    srcs = ["test/ncqp_solver_test.cc"],
    deps = [
        ":convex_polygon_set_constraint",
        ":ncqp_solver",
    ],
)
