load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc_walking_debug_visualizer",
    srcs = ["id_mpc_walking_debug_visualizer.cc"],
    hdrs = ["id_mpc_walking_debug_visualizer.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "@drake//:drake_shared_library",
    ],
)
