load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "cassie_mpc_utils",
    srcs = ["cassie_mpc_utils.cc"],
    hdrs = ["cassie_mpc_utils.h"],
    deps = [
        "//examples/Cassie:cassie_fixed_point_solver",
        "//examples/Cassie:cassie_utils",
        "//systems/controllers/id_mpc",
        "//systems/controllers/id_mpc/systems:walking_reference_system",
    ],
)

cc_binary(
    name = "run_id_mpc_standing",
    srcs = ["run_id_mpc_standing.cc"],
    deps = [
        ":cassie_mpc_utils",
        "//lcmtypes:lcmt_robot",
        "//systems:robot_lcm_systems",
        "//systems/controllers/id_mpc/systems:id_mpc_systems",
        "//systems/framework:lcm_driven_loop",
    ],
)

cc_binary(
    name = "run_id_mpc_walking",
    srcs = ["run_id_mpc_walking.cc"],
    deps = [
        ":cassie_mpc_utils",
        "//lcmtypes:lcmt_robot",
        "//systems:robot_lcm_systems",
        "//systems/controllers/id_mpc/systems:id_mpc_systems",
        "//systems/framework:lcm_driven_loop",
    ],
)

cc_binary(
    name = "visualizer",
    srcs = ["visualizer.cc"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//systems:plant_visualizer",
        "//systems:robot_lcm_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "run_joint_controller",
    srcs = ["run_joint_controller.cc"],
    deps = [
        "//systems:robot_lcm_systems",
        "//systems/controllers/id_mpc/systems:joint_pd_controller",
        "//systems/framework:lcm_driven_loop",
    ],
)
