package(default_visibility = ["//visibility:private"])

cc_library(
    name = "urdfs",
    data = glob([
        "urdf/**",
    ]),
)

cc_library(
    name = "mujoco_xml",
    data = glob([
        "mujoco_xml/**/*",
    ]),
)

filegroup(
    name = "all_parameter_yamls",
    visibility = ["//visibility:public"],
    data = glob(["parameters/*.yaml"]),
)

cc_library(
    name = "parallel_gripper_controller",
    srcs = [
        "parallel_gripper_controller.cc",
    ],
    hdrs = [
        "parallel_gripper_controller.h",
    ],
    deps = [
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "deformable_common",
    srcs = [
        "deformable_common.cc",
    ],
    hdrs = [
        "deformable_common.h",
    ],
    deps = [
        "//common:find_resource",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "pick_up_round_belt",
    srcs = [
        "pick_up_round_belt.cc",
    ],
    data = [
        "@drake_models//:wsg_50_description",
    ],
    deps = [
        ":deformable_common",
        ":parallel_gripper_controller",
        "//common:find_resource",
        "@mujoco//:mujoco",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "round_belt_sim",
    srcs = [
        "round_belt_sim.cc",
    ],
    data = [
        ":all_parameter_yamls",
        ":urdfs",
        "@drake_models//:franka_description",
    ],
    deps = [
        "//common:find_resource",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//examples/belt_assembly/parameter_headers:lcm_channel_params",
        "//examples/belt_assembly/parameter_headers:round_belt_sim_params",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "round_belt_visualizer",
    srcs = [
        "round_belt_visualizer.cc",
    ],
    data = [
        ":all_parameter_yamls",
        ":urdfs",
        "@drake_models//:franka_description",
    ],
    deps = [
        "//common:find_resource",
        "//common:eigen_utils",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//examples/belt_assembly/parameter_headers:lcm_channel_params",
        "//examples/belt_assembly/parameter_headers:visualizer_params",
        "//lcmtypes:lcmt_robot",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)
