load(
    "@drake//tools/skylark:java.bzl",
    "java_binary",
)
load(
    "@lcm//lcm-bazel:lcm_cc_library_srcs.bzl",
    "lcm_cc_library_srcs",
)
load(
    "@lcm//lcm-bazel:lcm_java_library_srcs.bzl",
    "lcm_java_library_srcs",
)
load(
    "@lcm//lcm-bazel:lcm_library.bzl",
    "lcm_library",
)
load(
    "@lcm//lcm-bazel:lcm_py_library_srcs.bzl",
    "lcm_py_library_srcs",
)
load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_java//java:java_library.bzl", "java_library")
load("@rules_python//python:defs.bzl", "py_library")

package(default_visibility = ["//visibility:public"])

ALL_LCM_SRCS = glob(["*.lcm"])

ALL_ARCHIVE_LCM_SRCS = glob(["archive/*.lcm"])

lcm_library(
    name = "messages",
    srcs = ALL_LCM_SRCS,
    lcm_package = "dairlib",
    visibility = ["//visibility:public"],
)

lcm_library(
    name = "archive_messages",
    srcs = ALL_ARCHIVE_LCM_SRCS,
    lcm_package = "archive.dairlib",
    visibility = ["//visibility:public"],
)

lcm_cc_library_srcs(
    name = "messages_cc_srcs",
    src = ":messages",
)

lcm_cc_library_srcs(
    name = "archive_messages_cc_srcs",
    src = ":archive_messages",
)

cc_library(
    name = "lcmt_robot_archive",
    srcs = [":archive_messages_cc_srcs"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = ["@lcm//lcm:lcm-coretypes"],
)

cc_library(
    name = "lcmt_robot",
    srcs = [":messages_cc_srcs"],
    includes = ["."],
    visibility = ["//visibility:public"],
    deps = ["@lcm//lcm:lcm-coretypes"],
)

lcm_java_library_srcs(
    name = "messages_java_srcs",
    src = ":messages",
)

lcm_java_library_srcs(
    name = "archive_messages_java_srcs",
    src = ":archive_messages",
)

java_library(
    name = "lcmtypes_robot_java",
    srcs = [":messages_java_srcs"],
    visibility = ["//visibility:public"],
    deps = ["@lcm//lcm-java"],
)

java_library(
    name = "lcmtypes_robot_archive_java",
    srcs = [":archive_messages_java_srcs"],
    visibility = ["//visibility:public"],
    deps = ["@lcm//lcm-java"],
)

lcm_py_library_srcs(
    name = "messages_py_srcs",
    src = ":messages",
)

lcm_py_library_srcs(
    name = "archive_messages_py_srcs",
    src = ":archive_messages",
)

py_library(
    name = "lcmtypes_robot_py",
    srcs = [":messages_py_srcs"],
    imports = ["."],
    visibility = ["//visibility:public"],
)

py_library(
    name = "lcmtypes_robot_archive_py",
    srcs = [":archive_messages_py_srcs"],
    imports = ["."],
    visibility = ["//visibility:public"],
)

java_binary(
    name = "dair-lcm-spy",
    main_class = "lcm.spy.Spy",
    visibility = ["//visibility:private"],
    runtime_deps = [
        ":lcmtypes_robot_java",
        "@c3//lcmtypes:lcmtypes_c3_java",
        "@drake//lcmtypes:lcmtypes_drake_java",
    ],
)
