load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "simulation_utils",
    srcs = [
        "simulation_utils.cc",
    ],
    hdrs = [
        "simulation_utils.h",
    ],
    deps = [
        "@drake//:drake_shared_library",
    ],
)
