cc_binary(
    name = "mesh_sampling_buffer",
    srcs = [
        "mesh_sampling_buffer.cc",
    ],
    copts = [
        "-I/usr/include/eigen3",
    ],
    linkopts=[
        "-lstdc++",
        "-lboost_system", 
        "-lboost_filesystem", 
        "-lgmp", 
        "-lmpfr",
    ]
)

cc_binary(
    name = "mesh_sampling_libigl",
    srcs = [
        "mesh_sampling_libigl.cc",
    ],
    copts = [
        "-I/usr/include/eigen3",
        "-I/usr/include/libigl/include",
    ],
    linkopts=[
        "-lstdc++",
        "-lboost_system", 
        "-lboost_filesystem", 
        "-lgmp", 
        "-lmpfr",
    ]
)