//
// Created by brian on 12/16/21.
//

#ifndef DAIRLIB_DAIRLIB_EXAMPLES_CASSIE_MPC_ANGULAR_MOMENTUM_TRAJ_GEN_H_
#define DAIRLIB_DAIRLIB_EXAMPLES_CASSIE_MPC_ANGULAR_MOMENTUM_TRAJ_GEN_H_

#endif //DAIRLIB_DAIRLIB_EXAMPLES_CASSIE_MPC_ANGULAR_MOMENTUM_TRAJ_GEN_H_
