load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc_systems",
    deps = [
        ":constant_reference_system",
        ":id_mpc_system",
    ],
)

cc_library(
    name = "id_mpc_system",
    srcs = ["id_mpc_system.cc"],
    hdrs = ["id_mpc_system.h"],
    deps = [
        ":mpc_solution",
        "//lcmtypes:lcmt_robot",
        "//systems/controllers/id_mpc",
        "//systems/controllers/id_mpc/sqp:id_mpc_sqp",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "constant_reference_system",
    srcs = ["constant_reference_system.cc"],
    hdrs = ["constant_reference_system.h"],
    deps = [
        "//systems/controllers/id_mpc/costs:id_mpc_costs",
    ],
)

cc_library(
    name = "walking_reference_system",
    srcs = ["walking_reference_system.cc"],
    hdrs = ["walking_reference_system.h"],
    deps = [
        "//systems/framework:vector",
        "//systems/controllers/id_mpc/costs:id_mpc_costs",
    ],
)

cc_library(
    name = "mpc_solution",
    srcs = ["mpc_solution.cc"],
    hdrs = ["mpc_solution.h"],
    deps = [
        "//lcm:lcm_trajectory_saver",
        "//systems/controllers/id_mpc/sqp:id_mpc_sqp",
    ],
)

cc_library(
    name = "joint_pd_controller",
    srcs = ["joint_pd_controller.cc"],
    hdrs = [
        "joint_controller_gains.h",
        "joint_pd_controller.h"
    ],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "//multibody:utils",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ]
)