load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc_systems",
    deps = [
        ":constant_reference_system",
        ":id_mpc_system",
        ":id_mpc_walking_system",
    ],
)

cc_library(
    name = "id_mpc_system",
    srcs = ["id_mpc_system.cc"],
    hdrs = ["id_mpc_system.h"],
    deps = [
        ":mpc_solution",
        "//lcmtypes:lcmt_robot",
        "//systems/controllers/id_mpc",
        "//solvers/sqp",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "id_mpc_walking_system",
    srcs = ["id_mpc_walking_system.cc"],
    hdrs = ["id_mpc_walking_system.h"],
    deps = [
        ":mpc_solution",
        "//lcmtypes:lcmt_robot",
        "//multibody:utils",
        "//systems/controllers/id_mpc",
        "//solvers/sqp",
        "//systems/controllers/id_mpc/walking:id_mpc_walking",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "constant_reference_system",
    srcs = ["constant_reference_system.cc"],
    hdrs = ["constant_reference_system.h"],
    deps = [
        "//systems/controllers/id_mpc/references:id_mpc_references",
    ],
)

cc_library(
    name = "mpc_solution",
    srcs = ["mpc_solution.cc"],
    hdrs = ["mpc_solution.h"],
    deps = [
        "//lcm:lcm_trajectory_saver",
        "//solvers/sqp",
    ],
)

cc_library(
    name = "joint_pd_controller",
    srcs = ["joint_pd_controller.cc"],
    hdrs = [
        "joint_controller_gains.h",
        "joint_pd_controller.h",
    ],
    deps = [
        "//lcm:lcm_trajectory_saver",
        "//lcmtypes:lcmt_robot",
        "//multibody:utils",
        "//systems/controllers/id_mpc/core:solution_trajectories",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)
