cc_binary(
    name = "trifinger_sim",
    srcs = ["trifinger_sim.cc"],
    data = [
        "//examples/cube_flip:urdfs",
    ],
    deps = [
        # ":parameters",
        "//common",
        "//examples/cube_flip/trifinger/parameter_headers:trifinger_lcm_channels",
        "//examples/cube_flip/trifinger/parameter_headers:trifinger_sim_params",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        "//multibody/kinematic",
        "@drake//:drake_shared_library",
        "@gflags",

    ],
)


cc_binary(
    name = "trifinger_osc_controller",
    srcs = ["trifinger_osc_controller.cc"],
    data = [
        "//examples/cube_flip:urdfs",
    ],
    deps = [
        # ":parameters",
        "//examples/cube_flip/trifinger/parameter_headers:trifinger_osc_controller_params",
        "//examples/cube_flip/trifinger/parameter_headers:trifinger_lcm_channels",
        "//examples/cube_flip/trifinger:trifinger_position_splitter",
        "//common",
        "//examples/franka/systems:franka_systems",
        "//lcm:lcm_trajectory_saver",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/controllers",
        "//systems/controllers/osc:operational_space_control",
        "//systems/framework:lcm_driven_loop",
        "//systems/primitives:radio_parser",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_library(
    name = "trifinger_position_splitter",
    srcs = [
        "trifinger_position_splitter.cc",
    ],
    hdrs = [
        "trifinger_position_splitter.h",
    ],
    deps = [
        "//common:eigen_utils",
        "//common:find_resource",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
    ],
)

cc_binary(
    name = "trifinger_visualizer",
    srcs = ["trifinger_visualizer.cc"],
    data = [
        "//examples/cube_flip:urdfs",
    ],
    deps = [
        "//examples/cube_flip/trifinger/parameter_headers:trifinger_lcm_channels",
        "//examples/cube_flip/trifinger/parameter_headers:trifinger_sim_params",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)
