load("@drake//tools/lint:lint.bzl", "add_lint_tests")

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "id_mpc_sqp",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
    deps = [
        "//solvers:osqp_wrapper",
        "//solvers:qp_data",
        "//solvers/admm:set_membership_constraint",
        "//systems/controllers/id_mpc/costs:id_mpc_costs",
        "@drake//:drake_shared_library",
    ],
)
