package(default_visibility = ["//visibility:public"])

cc_library(
    name = "systems",
    deps = [
        ":franka_kinematics",
        ":franka_kinematics_vector",
        ":franka_state_translator",
        ":franka_target_joint_position_receiver",
        ":robot_lcm_systems",
        ":vector_scope",
        ":system_utils",
        "//systems/controllers:controllers",
        "//systems/filters:filters",
        "//systems/framework:framework",
        "//systems/primitives:primitives",
        "//systems/trajectory_optimization:trajectory_optimization",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "robot_lcm_systems",
    srcs = ["robot_lcm_systems.cc"],
    hdrs = [
        "robot_lcm_systems.h",
    ],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//multibody:utils",
        "//systems/framework:vector",
        "//systems/primitives",
        "@drake//:drake_shared_library",
        "@lcm",
    ],
)

cc_library(
    name = "vector_scope",
    srcs = ["vector_scope.cc"],
    hdrs = ["vector_scope.h"],
    deps = [
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "system_utils",
    srcs = ["system_utils.cc"],
    hdrs = ["system_utils.h"],
    deps = [
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "franka_kinematics",
    srcs = ["franka_kinematics.cc"],
    hdrs = ["franka_kinematics.h"],
    deps = [
        ":franka_kinematics_vector",
        "//common",
        "//lcmtypes:lcmt_robot",
        "//multibody:utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "franka_kinematics_vector",
    srcs = ["franka_kinematics_vector.cc"],
    hdrs = ["franka_kinematics_vector.h"],
    deps = [
        "//common",
        "//multibody:utils",
        "//systems/primitives",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "franka_state_translator",
    srcs = [
        "franka_state_translator.cc",
    ],
    hdrs = [
        "franka_state_translator.h",
    ],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)

cc_library(
    name = "franka_target_joint_position_receiver",
    srcs = ["franka_target_joint_position_receiver.cc"],
    hdrs = [
        "franka_target_joint_position_receiver.h",
    ],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//systems/framework:vector",
        "@drake//:drake_shared_library",
    ],
)

filegroup(
    name = "headers",
    srcs = glob([
        "*.h",
        "**/*.h",
    ]),
)
