#!/bin/bash
WORKSPACE_DIR="${PWD}"
while [[ "${WORKSPACE_DIR}" != / ]]; do
    if [[ -e "${WORKSPACE_DIR}/WORKSPACE" ]]; then
      break;
    fi
    WORKSPACE_DIR="$(dirname "${WORKSPACE_DIR}")"
done
readonly WORKSPACE_DIR

if [ "${DAIRLIB_BUILD_PERCEPTIVE_LOCOMOTION_HARDWARE_DEPS}" == "ON" ] ; then
  exec -a "$0" "${BAZEL_REAL}" "--bazelrc=${WORKSPACE_DIR}/perception_hardware.bazelrc" "$@"
else
  exec -a "$0" "${BAZEL_REAL}" "--bazelrc=${WORKSPACE_DIR}/standard.bazelrc" "$@"
fi
