#ifndef CASSIE_NETWORKING_H
#define CASSIE_NETWORKING_H

#define CASSIE_STATE_LCM_CHANNEL "CASSIE_STATE"
#define CASSIE_INPUT_LCM_CHANNEL "CASSIE_INPUT"
#define CASSIE_TELEMETRY_LCM_CHANNEL "CASSIE_TELEMETRY"
#define CASSIE_PD_CONFIG_LCM_CHANNEL "PD_CONFIG"
#define CASSIE_UDP_LOCAL_ADDR "10.10.10.100"
#define CASSIE_UDP_REMOTE_ADDR "10.10.10.3"

#define CASSIE_LCM_BROADCAST_URL std::string("udpm://239.255.76.67:7667?ttl=1")

#define CASSIE_UDP_LOCAL_PORT 25001
#define CASSIE_UDP_REMOTE_PORT 25000

#endif
