#ifndef CASSIE_NETWORKING_H
#define CASSIE_NETWORKING_H

#define CASSIE_STATE_LCM_CHANNEL "CASSIE_STATE"
#define CASSIE_INPUT_LCM_CHANNEL "CASSIE_INPUT"
#define CASSIE_PD_CONFIG_LCM_CHANNEL "PD_CONFIG"
#define CASSIE_UDP_LOCAL_ADDR "10.10.10.100"
#define CASSIE_UDP_REMOTE_ADDR "10.10.10.3"
#define CASSIE_UDP_LOCAL_PORT 5000
#define CASSIE_UDP_REMOTE_PORT 5000

#endif
