"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""


from io import BytesIO
import struct

import dairlib

class lcmt_densetact_measurement_data(object):
    """
      Collection of DenseTact data
    
    """

    __slots__ = ["numSensors", "sensorData"]

    __typenames__ = ["int8_t", "dairlib.lcmt_densetact_measurement"]

    __dimensions__ = [None, ["numSensors"]]

    def __init__(self):
        self.numSensors = 0
        """ LCM Type: int8_t """
        self.sensorData = []
        """ LCM Type: dairlib.lcmt_densetact_measurement[numSensors] """

    def encode(self):
        buf = BytesIO()
        buf.write(lcmt_densetact_measurement_data._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">b", self.numSensors))
        for i0 in range(self.numSensors):
            assert self.sensorData[i0]._get_packed_fingerprint() == dairlib.lcmt_densetact_measurement._get_packed_fingerprint()
            self.sensorData[i0]._encode_one(buf)

    @staticmethod
    def decode(data: bytes):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != lcmt_densetact_measurement_data._get_packed_fingerprint():
            raise ValueError("Decode error")
        return lcmt_densetact_measurement_data._decode_one(buf)

    @staticmethod
    def _decode_one(buf):
        self = lcmt_densetact_measurement_data()
        self.numSensors = struct.unpack(">b", buf.read(1))[0]
        self.sensorData = []
        for i0 in range(self.numSensors):
            self.sensorData.append(dairlib.lcmt_densetact_measurement._decode_one(buf))
        return self

    @staticmethod
    def _get_hash_recursive(parents):
        if lcmt_densetact_measurement_data in parents: return 0
        newparents = parents + [lcmt_densetact_measurement_data]
        tmphash = (0x5eb95ea8bc9c69bf+ dairlib.lcmt_densetact_measurement._get_hash_recursive(newparents)) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff) + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _packed_fingerprint = None

    @staticmethod
    def _get_packed_fingerprint():
        if lcmt_densetact_measurement_data._packed_fingerprint is None:
            lcmt_densetact_measurement_data._packed_fingerprint = struct.pack(">Q", lcmt_densetact_measurement_data._get_hash_recursive([]))
        return lcmt_densetact_measurement_data._packed_fingerprint

    def get_hash(self):
        """Get the LCM hash of the struct"""
        return struct.unpack(">Q", lcmt_densetact_measurement_data._get_packed_fingerprint())[0]

