/** THIS IS AN AUTOMATICALLY GENERATED FILE.  DO NOT MODIFY
 * BY HAND!!
 *
 * Generated by lcm-gen 1.5.1
 **/

#ifndef __dairlib_lcmt_saved_traj_hpp__
#define __dairlib_lcmt_saved_traj_hpp__

#include <lcm/lcm_coretypes.h>

#include <vector>
#include <string>
#include "dairlib/lcmt_metadata.hpp"
#include "dairlib/lcmt_trajectory_block.hpp"

namespace dairlib
{

/**
 *   lcmtype analog for LcmTrajectory to enable using a LcmSerializer to 
 *     save/load trajectories
 *
 */
class lcmt_saved_traj
{
    public:
        dairlib::lcmt_metadata metadata;

        int32_t    num_trajectories;

        /**
         * LCM Type: dairlib.lcmt_trajectory_block[num_trajectories]
         */
        std::vector< dairlib::lcmt_trajectory_block > trajectories;

        /**
         * LCM Type: string[num_trajectories]
         */
        std::vector< std::string > trajectory_names;

    public:
        /**
         * Encode a message into binary form.
         *
         * @param buf The output buffer.
         * @param offset Encoding starts at thie byte offset into @p buf.
         * @param maxlen Maximum number of bytes to write.  This should generally be
         *  equal to getEncodedSize().
         * @return The number of bytes encoded, or <0 on error.
         */
        inline int encode(void *buf, int offset, int maxlen) const;

        /**
         * Check how many bytes are required to encode this message.
         */
        inline int getEncodedSize() const;

        /**
         * Decode a message from binary form into this instance.
         *
         * @param buf The buffer containing the encoded message.
         * @param offset The byte offset into @p buf where the encoded message starts.
         * @param maxlen The maximum number of bytes to read while decoding.
         * @return The number of bytes decoded, or <0 if an error occured.
         */
        inline int decode(const void *buf, int offset, int maxlen);

        /**
         * Retrieve the 64-bit fingerprint identifying the structure of the message.
         * Note that the fingerprint is the same for all instances of the same
         * message type, and is a fingerprint on the message type definition, not on
         * the message contents.
         */
        inline static int64_t getHash();

        /**
         * Returns "lcmt_saved_traj"
         */
        inline static const char* getTypeName();

        // LCM support functions. Users should not call these
        inline int _encodeNoHash(void *buf, int offset, int maxlen) const;
        inline int _getEncodedSizeNoHash() const;
        inline int _decodeNoHash(const void *buf, int offset, int maxlen);
        inline static uint64_t _computeHash(const __lcm_hash_ptr *p);
};

int lcmt_saved_traj::encode(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;
    int64_t hash = getHash();

    tlen = __int64_t_encode_array(buf, offset + pos, maxlen - pos, &hash, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = this->_encodeNoHash(buf, offset + pos, maxlen - pos);
    if (tlen < 0) return tlen; else pos += tlen;

    return pos;
}

int lcmt_saved_traj::decode(const void *buf, int offset, int maxlen)
{
    int pos = 0, thislen;

    int64_t msg_hash;
    thislen = __int64_t_decode_array(buf, offset + pos, maxlen - pos, &msg_hash, 1);
    if (thislen < 0) return thislen; else pos += thislen;
    if (msg_hash != getHash()) return -1;

    thislen = this->_decodeNoHash(buf, offset + pos, maxlen - pos);
    if (thislen < 0) return thislen; else pos += thislen;

    return pos;
}

int lcmt_saved_traj::getEncodedSize() const
{
    return 8 + _getEncodedSizeNoHash();
}

int64_t lcmt_saved_traj::getHash()
{
    static int64_t hash = static_cast<int64_t>(_computeHash(NULL));
    return hash;
}

const char* lcmt_saved_traj::getTypeName()
{
    return "lcmt_saved_traj";
}

int lcmt_saved_traj::_encodeNoHash(void *buf, int offset, int maxlen) const
{
    int pos = 0, tlen;

    tlen = this->metadata._encodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_encode_array(buf, offset + pos, maxlen - pos, &this->num_trajectories, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    for (int a0 = 0; a0 < this->num_trajectories; a0++) {
        tlen = this->trajectories[a0]._encodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    for (int a0 = 0; a0 < this->num_trajectories; a0++) {
        char* __cstr = const_cast<char*>(this->trajectory_names[a0].c_str());
        tlen = __string_encode_array(
            buf, offset + pos, maxlen - pos, &__cstr, 1);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    return pos;
}

int lcmt_saved_traj::_decodeNoHash(const void *buf, int offset, int maxlen)
{
    int pos = 0, tlen;

    tlen = this->metadata._decodeNoHash(buf, offset + pos, maxlen - pos);
    if(tlen < 0) return tlen; else pos += tlen;

    tlen = __int32_t_decode_array(buf, offset + pos, maxlen - pos, &this->num_trajectories, 1);
    if(tlen < 0) return tlen; else pos += tlen;

    try {
        this->trajectories.resize(this->num_trajectories);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_trajectories; a0++) {
        tlen = this->trajectories[a0]._decodeNoHash(buf, offset + pos, maxlen - pos);
        if(tlen < 0) return tlen; else pos += tlen;
    }

    try {
        this->trajectory_names.resize(this->num_trajectories);
    } catch (...) {
        return -1;
    }
    for (int a0 = 0; a0 < this->num_trajectories; a0++) {
        int32_t __elem_len;
        tlen = __int32_t_decode_array(
            buf, offset + pos, maxlen - pos, &__elem_len, 1);
        if(tlen < 0) return tlen; else pos += tlen;
        if(__elem_len > maxlen - pos) return -1;
        this->trajectory_names[a0].assign(static_cast<const char*>(buf) + offset + pos, __elem_len -  1);
        pos += __elem_len;
    }

    return pos;
}

int lcmt_saved_traj::_getEncodedSizeNoHash() const
{
    int enc_size = 0;
    enc_size += this->metadata._getEncodedSizeNoHash();
    enc_size += __int32_t_encoded_array_size(NULL, 1);
    for (int a0 = 0; a0 < this->num_trajectories; a0++) {
        enc_size += this->trajectories[a0]._getEncodedSizeNoHash();
    }
    for (int a0 = 0; a0 < this->num_trajectories; a0++) {
        enc_size += this->trajectory_names[a0].size() + 4 + 1;
    }
    return enc_size;
}

uint64_t lcmt_saved_traj::_computeHash(const __lcm_hash_ptr *p)
{
    const __lcm_hash_ptr *fp;
    for(fp = p; fp != NULL; fp = fp->parent)
        if(fp->v == lcmt_saved_traj::getHash)
            return 0;
    const __lcm_hash_ptr cp = { p, lcmt_saved_traj::getHash };

    uint64_t hash = 0xf95e856dc25c6f0fLL +
         dairlib::lcmt_metadata::_computeHash(&cp) +
         dairlib::lcmt_trajectory_block::_computeHash(&cp);

    return (hash<<1) + ((hash>>63)&1);
}

}

#endif
