services:
  trifinger-env:
    init: true
    image: trifinger_dev:1.0
    container_name: trifinger_dev
    stop_signal: SIGINT
    command: ['sleep', 'infinity']
    privileged: true
    network_mode: host
    working_dir: /home
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - ~/git/Trifinger/workspace:/home
    environment:
      - DISPLAY=${DISPLAY}
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1 # corresponds to 'unlimited'
      memlock: 8428281856
