package(default_visibility = ["//visibility:public"])

cc_library(
    name = "franka_visualizer_diagram",
    srcs = ["franka_visualizer_diagram.cc"],
    hdrs = ["franka_visualizer_diagram.h"],
    data = [
        "//examples/jacktoy:urdfs",
        "@drake//manipulation/models/franka_description:models",
    ],
    deps = [
        "//examples/jacktoy:franka_lcm_channels",
        "//examples/jacktoy:franka_sim_params",
        "//examples/jacktoy:franka_c3_controller_params",
        "//systems/controllers:sampling_params",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//examples/jacktoy/systems:franka_systems",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
)

cc_binary(
    name = "test",
    srcs = ["test.cc"],
    deps = [
        ":franka_visualizer_diagram",
    ],
)