package(default_visibility = ["//visibility:public"])


cc_library(
    name = "visualization_parameters",
    data = glob([
        "parameters/*.yaml",
    ]),
)


cc_binary(
    name = "trajectory_visualizer_plate",
    srcs = ["trajectory_visualizer_plate.cc"],
    data = [
        "//examples/iC3:urdfs",
        "//examples/iC3:parameters",
    ],
    deps = [
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization:trajectory_lcm_parser_plate",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)

cc_binary(
    name = "trajectory_visualizer_hand",
    srcs = ["trajectory_visualizer_hand.cc"],
    data = [
        "//examples/iC3:urdfs",
        "//examples/iC3:parameters",
        "@drake_models//:allegro_hand_description",
    ],
    deps = [
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization:trajectory_lcm_parser_hand",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)

cc_binary(
    name = "trajectory_visualizer_point_hand",
    srcs = ["trajectory_visualizer_point_hand.cc"],
    data = [
        "//examples/iC3:urdfs",
        "//examples/iC3:parameters",
    ],
    deps = [
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization:trajectory_lcm_parser_point_hand",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)


cc_binary(
    name = "trajectory_visualizer_point_hand_slider",
    srcs = ["trajectory_visualizer_point_hand_slider.cc"],
    data = [
        "//examples/iC3:urdfs",
        "//examples/iC3:parameters",
    ],
    deps = [
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization:point_hand_pose_getter",
        "//examples/iC3/visualization:meshcat_slider_system",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)


cc_binary(
    name = "trajectory_video_plate",
    srcs = ["trajectory_video_plate.cc"],
    data = [
        "//examples/iC3:urdfs",
        "//examples/iC3:parameters",
    ],
    deps = [
        "//examples/iC3/visualization/parameter_headers:trajectory_video_params",
        "//examples/iC3/visualization:lcm_pose_getter",
        "//examples/iC3/visualization:meshcat_slider_system",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)


cc_binary(
    name = "trajectory_video_point_hand",
    srcs = ["trajectory_video_point_hand.cc"],
    data = [
        "//examples/iC3:urdfs",
        "//examples/iC3:parameters",
    ],
    deps = [
        "//examples/iC3/visualization/parameter_headers:trajectory_video_params",
        "//examples/iC3/visualization:lcm_pose_getter",
        "//examples/iC3/visualization:meshcat_slider_system",
        "//common",
        "//multibody:utils",
        "//multibody:visualization_utils",
        "//systems/senders:senders",
        "//systems:robot_lcm_systems",
        "//systems:system_utils",
        "//systems/primitives",
        "//systems/trajectory_optimization:lcm_trajectory_systems",
        "//systems/visualization:lcm_visualization_systems",
        "@drake//:drake_shared_library",
        "@gflags",
    ],
    linkopts = [
        "-L/lib/x86_64-linux-gnu",
        "-lopenblas",
    ],
)


cc_library(
    name = "meshcat_slider_system",
    hdrs = ["meshcat_slider_system.h"],
    deps = [
        "@drake//:drake_shared_library",
    ],
)


cc_library(
    name = "trajectory_lcm_parser_plate",
    srcs = ["trajectory_lcm_parser_plate.cc"],
    hdrs = ["trajectory_lcm_parser_plate.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
    ],
)

cc_library(
    name = "trajectory_lcm_parser_hand",
    srcs = ["trajectory_lcm_parser_hand.cc"],
    hdrs = ["trajectory_lcm_parser_hand.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
    ],
)

cc_library(
    name = "trajectory_lcm_parser_point_hand",
    srcs = ["trajectory_lcm_parser_point_hand.cc"],
    hdrs = ["trajectory_lcm_parser_point_hand.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
    ],
)

cc_library(
    name = "plate_pose_getter",
    srcs = ["plate_pose_getter.cc"],
    hdrs = ["plate_pose_getter.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization/parameter_headers:trajectory_video_params",

    ],
)

cc_library(
    name = "point_hand_pose_getter",
    srcs = ["point_hand_pose_getter.cc"],
    hdrs = ["point_hand_pose_getter.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization/parameter_headers:trajectory_video_params",

    ],
)

cc_library(
    name = "lcm_pose_getter",
    srcs = ["lcm_pose_getter.cc"],
    hdrs = ["lcm_pose_getter.h"],
    deps = [
        "//lcmtypes:lcmt_robot",
        "//lcm:lcm_trajectory_saver",
        "@drake//:drake_shared_library",
        "//examples/iC3/visualization/parameter_headers:trajectory_visualizer_params",
        "//examples/iC3/visualization/parameter_headers:trajectory_video_params",
    ],
)

