package(default_visibility = ["//visibility:public"])

py_binary(
    name = "test_spacemouse_osc",
    srcs = ["test_spacemouse_osc.py"],
    deps = [
        "//lcmtypes:lcmtypes_robot_py",
    ],
)

py_binary(
    name = "test_trajectory_osc",
    srcs = ["test_trajectory_osc.py"],
    data = [
        "@drake_models//:franka_description",
    ],
    deps = [
        "//bindings/pydairlib/lcm:lcm",
        "//lcmtypes:lcmtypes_robot_py",
    ],
)

py_binary(
    name = "test_schunk_command",
    srcs = ["test_schunk_command.py"],
    deps = [
        "//bindings/pydairlib/lcm:lcm",
        "//lcmtypes:lcmtypes_robot_py",
    ],
)